// <auto-generated />
using BooksAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BooksAPI.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20190806015238_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("BooksAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author")
                        .IsRequired();

                    b.Property<string>("Category")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Author 1",
                            Category = "Fiction",
                            Title = "The Grapes of Wrath"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Author 2",
                            Category = "Fiction",
                            Title = "Cannery Row"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Author 3",
                            Category = "Fiction",
                            Title = "The Shining"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
